#!/bin/sh

#if [ "$(bspc query -N -d focused -n .window.\!hidden)" == "" ]; then

count=$(herbstclient attr tags.focus.client_count)
if [ $count -eq 0 ]; then
	echo "No windows on desktop"
else
	echo "Windows on desktop"
fi
