#! /bin/sh

##############################################
# _                                          
#| |__  ___ _ ____      ___ __ ___  _ __ ___ 
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#| |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#          |_|                               
##############################################

zsh ~/.config/bspwm/killscript;
sxhkd & 

###Config

#bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor eDP -d          
#zsh ~/.config/bspwm/monitorsetup &
bspc monitor "eDP1" -d          

bspc config border_width        12
bspc config top_padding         36
bspc config right_padding       -4
bspc config left_padding        -4
bspc config bottom_padding      -4
bspc config window_gap          16
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

. "${HOME}/Public/misc/colorschemes/forest-night-xresources/forest-night.sh"
bspc config focused_border_color "$background"
bspc config normal_border_color  "$background"
bspc config active_border_color  "$background"
bspc config presel_feedback_color "$color2"
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true

###Rules
bspc rule -a "Zathura"	state=tiled
bspc rule -a Termite:cmatrixterm state=fullscreen
bspc rule -a Termite:dropdown state=floating
bspc rule -a Termite:applauncher state=floating rectangle=406x504+753+285
bspc rule -a Termite:greenclip state=floating rectangle=688x400+612+337
bspc rule -a Termite:bsphidwins state=floating rectangle=448x413+732+331
bspc rule -a Termite:findFiles state=floating rectangle=610x647+651+214
bspc rule -a Termite:sxhkdhelp state=floating rectangle=736x491+588+292
bspc rule -a Termite:splatmoji state=floating 
bspc rule -a Termite:powermenu state=floating rectangle=280x309+816+383
bspc rule -a Termite:fzfnotes state=floating 
bspc rule -a Termite:google state=floating
bspc rule -a Termite:bluetooth state=floating rectangle=268x270+822+402
bspc rule -a Termite:notifHistory state=floating
bspc rule -a Termite:window state=floating rectangle=370x400+771+337
bspc rule -a Termite:navi state=floating
bspc rule -a Termite:bashmount state=floating rectangle=580x244+666+415
#bspc rule -a "Emacs" state=tiled
bspc rule -a "feh" state=floating
bspc rule -a "mpv" state=floating
#bspc rule -a "Gifview" state=floating
bspc rule -a "scrcpy" state=floating

## Non-bspwm specific settings
#xset s 420 179
xset r rate 440 50
xset +fp ~/.fonts/misc/ 
#xset +fp ~/.fonts/misc/tamsyn-font-1.11/ 
xsetroot -cursor_name left_ptr &
xmodmap -e "keysym Menu = Super_R" &
numlockx &
sudo bluetooth off
export PIDSWALLOW_SWALLOW_COMMAND='bspc node $pwid --flag hidden=on'
export PIDSWALLOW_VOMIT_COMMAND='bspc node $pwid --flag hidden=off'
export PIDSWALLOW_PREGLUE_HOOK='bspc query -N -n $pwid.floating >/dev/null && bspc node $cwid --state floating'

###Application startup
#wal -R -n -q
#~/.config/bspwm/xwinwrap &
picom --config ~/.config/bspwm/phicom.conf &
~/.fehbg2 &
~/.config/polybar/launch.sh &
#phicom --config ~/.config/bspwm/phicom.conf &
/usr/lib/geoclue-2.0/demos/agent &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
#~/.fehbg &
#tiramisu -j | tee -a /tmp/output /tmp/output2 &
dunst &
unclutter &
desknamer &
#xss-lock -n ~/.config/bspwm/.screensaver -l -- ~/.config/bspwm/i3lock.sh &
light-locker --lock-on-suspend --lock-on-lid --idle-hint &
~/.config/bspwm/localserver &
greenclip daemon &
an2linuxserver.py &
~/.config/bspwm/borders &
#flashfocus &
~/.config/bspwm/pulse-volume-watcher.py | xob -s volume &
~/.config/bspwm/backlight-watcher-startup &
autoadb scrcpy -s '{}' &
pgrep -fl 'pidswallow -gl' || pidswallow -gl &
libinput-gestures-setup start &
sleep 3
blurwal --backend feh -m 1 &
clight --conf-file=/home/tetsomina/.config/clight.conf &
